### ISSUE TITLE
Combining topographic surfaces

### ISSUE THREAD

**Issue by jameshgrn** [badlands-model/pyBadlands-Companion#2]
Hi all, 

awesome project, super excited to dig my teeth in...I was wondering about this sentence from the topoCreate notebook in the companion folder on the docker image 

"Combining these simple forms it is possible to create some complex geometries that will have the desired format for running a badlands simulation."

How would I go about doing this?

**Comment by tristan-salles** [comment]
Hi @jameshgrn,

Thank you for your interest in badlands. If you are willing to create a realistic topography from today's elevation, you can have a look at the `etopoGen.ipynb` notebook. The way the initial surface is set in badlands is defined in:

https://badlands.readthedocs.io/en/latest/xml.html#grid-structure

I have also added you to the slack channel where you might find some useful information and will be able to ask questions to other users.

Hope it helps.

Best
Tristan

**Comment by jameshgrn** [comment]
Thank you! I joined the group.

**Comment by tristan-salles** [comment]
:+1:
